[project]
name = "adk-openapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adk>=0.0.5",
    "google>=3.0.0",
    "google-adk>=1.10.0",
    "python-dotenv>=1.1.1",
]
